var jobRData = [
  {
    id: 1,
    postedOn: new Date(),
    title: "Web Researcher",
    type: "Full time",
    location: "Remote",
    companyName: "BPO Solutions",
    companyUrl: "Google.com",
    skills: ["Communication Skills", "Research on Product", "Research on People", "Research on Industries"],
    link: "https://BPOsolutions.com",
  },
  {
    id: 2,
    postedOn: new Date(),
    title: "Data Researcher",
    type: "Part time",
    location: "Office",
    companyName: "S&P Global Islamabad",
    companyUrl: "Yahoo.com",
    skills: ["Developing Bussines ", "Maintaining Bussiness","Initiatives towards Automation"],
    link: "https://S&PGlobal/jobs",
  },
  {
    id: 3,
    postedOn: new Date(),
    title: "Field Researcher",
    type: "Contract",
    location: "Remote",
    companyName: "Enablers",
    companyUrl: "https://Enablers.com",
    skills: ["Master in AI","Research methods", "Building Budget through Research"],
    link: "https://Enablers/careers",
  },
  {
    id: 4,
    postedOn: new Date(),
    title: "Research Analyst",
    type: "Contract",
    location: "Remote",
    companyName: "MicroMerger PVT Ltd.",
    companyUrl: "https://MicroMerger.com",
    skills: ["Coduct Validity","Vast Analysis Techniques in RND", "Writing Reports","Summary"],
    link: "https://MicroMerger/careers",
  },
];
export default jobRData;